name: deploy via ssh
on: 
  push:
    branches:
    - main
    
jobs:
  deploy:
    name: ssh deploy
    # You may pin to the exact commit or the version.
    # uses: easingthemes/ssh-deploy@16bb35ed0b6e568fa7554ebdf990fdc4c046b549
    uses: easingthemes/ssh-deploy@v5.0.0
    with:
      # Private key part of an SSH key pair
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # Remote host
      REMOTE_HOST: ${{ secrets.SSH_HOST }}
      # Remote user
      REMOTE_USER: ${{ secrets.SSH_USER }}
      # Remote port
      REMOTE_PORT: 22
      # Target directory
      TARGET: ${{ secrets.DEPLOY_DIR }}
      # Script to run on host machine after rsync
      SCRIPT_AFTER: ./workflow.sh
          
