name: deploy via ssh
on: 
  push:
    branches:
    - main
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Connect via ssh
        run: |
          'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
          ssh ${{ secrets.SSH_HOST }}
      - name: Git Pull
        run: |
          cd ${{ secrets.DEPLOY_DIR }}
          git reset --hard
          git pull
      - name: Start Workflow
        run: ./workflow.sh
